const swaggerAutogen = require('swagger-autogen')()

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:3333",
  basePath: "/",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      "name": "User",
      "description": "Endpoints"
    }
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header",       // can be "header", "query" or "cookie"
      name: "Authorization",  // name of the header, query parameter or cookie
      description: "token"
    }
  },
  security: [{
    "apiKeyAuth": []
  }],
  definitions: {
    
  }
}
const outputFile = 'src/utils/swagger-output.json'
const endpointsFiles = ['src/routes/*.js']

swaggerAutogen(outputFile, endpointsFiles, doc)

