const swaggerAutogen = require('swagger-autogen')()

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  host: "localhost:3333",
  basePath: "/",
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      "name": "User",
      "description": "Endpoints"
    }
  ],
  securityDefinitions: {
    apiKeyAuth: {
      type: "apiKey",
      in: "header",       // can be "header", "query" or "cookie"
      name: "Authorization",  // name of the header, query parameter or cookie
      description: "token"
    }
  },
  security: [{
    "apiKeyAuth": []
  }],
  definitions: {
    
  }
}
const outputFile = 'src/utils/swagger-output.json'
const endpointsFiles = ['src/routes/*.js']

//Ususarios
swaggerSpec.paths['/users'] = {
  "get": {
    "tags": [
      "User"
    ],
    "summary": "Listar todos os usuarios",
    "description": "Listar todos os usuarios",
    "produces": [
      "application/json"
    ],
    "responses": {
      "200": {
        "description": "OK"
      }
    }
  },
  "post": {
    "tags": [
      "User"
    ],
    "summary": "Cadastrar um usuario",
    "description": "Cadastrar um usuario",
    "produces": [
      "application/json"
    ],
    "parameters": [
      {
        "in": "body",
        "name": "body",
        "description": "Dados do usuario",
        "required": true,
        "schema": {
          "$ref": "#/definitions/User"
        }
      }
    ],
    "responses": {
      "201": {
        "description": "Created"
      }
    }
  }
}

swaggerAutogen(outputFile, endpointsFiles, doc)

